CREATE TABLE users(
  id UUID PRIMARY KEY,
  email CHARACTER vARYING(150) NOT NULL UNIQUE,
  first_name CHARACTER vARYING(100) NOT NULL,
  last_name CHARACTER VARYING(100) NOT NULL,
  password CHARACTER vARYING(30) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL  
);

CREATE TABLE todos(
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  title CHARACTER vARYING(100) NOT NULL,
  description CHARACTER VARYING(255) NOT NULL,
  due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT todos_fkey_user FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
